[33m[W 2022-03-23 16:43:12,033][39m Trial 0 failed because of the following error: NameError("name 'flattened_val_logits' is not defined")
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/16/mg5_s98x3yd90kq7mmfmk3pr0000gn/T/ipykernel_597/748172136.py", line 76, in objective_tcn_model_samp_en
    loss = opt_tcn.train(trial, custom_train_loader_samp_en, custom_val_loader_samp_en, config,
  File "/var/folders/16/mg5_s98x3yd90kq7mmfmk3pr0000gn/T/ipykernel_597/1913114686.py", line 140, in train
    wandb.log({"epoch": epoch, "train_logits": wandb.Histogram(flattened_train_logits), "val_logits": wandb.Histogram(flattened_val_logits), "train_loss": avg_sample_train_loss_epoch, "val_loss": avg_sample_val_loss_epoch}, step=log_step)
NameError: name 'flattened_val_logits' is not defined
[32m[I 2022-03-23 16:43:55,589][39m A new study created in memory with name: no-name-6318eac9-9da5-4645-9b86-7549e557faa9
Params: {'learning_rate': 0.09914343665997223, 'num_hidden_units_per_layer': 256, 'weight_decay': 0.0005259459568807791, 'kernel_size': 5, 'num_epochs': 10, 'drop_out': 0.11961039249711698, 'batch_size': 60, 'reduced_seq_length': 30, 'num_levels': 3, 'stride': 1, 'pos_weight': tensor([6.8261])}
[32m[I 2022-03-23 16:44:00,715][39m A new study created in memory with name: no-name-3e8d7c2c-fb77-4542-87d6-f222f6cadbba
The number of rows with infinite numbers that will be replaced with zero is: 0
The number of rows with NA numbers that will be replaced with zero is: 0
The number of rows with infinite numbers that will be replaced with zero is: 0
The number of rows with NA numbers that will be replaced with zero is: 0