Epoch [1/40] Training loss: 562914.9441152910
--------------------------------------------------
Epoch [2/40] Training loss: 7.3660078843
--------------------------------------------------
Epoch [3/40] Training loss: 3.6263060967
--------------------------------------------------
Epoch [4/40] Training loss: 3.6056390206
--------------------------------------------------
Epoch [5/40] Training loss: 3.0562349558
--------------------------------------------------
Epoch [6/40] Training loss: 2.6984341542
--------------------------------------------------
Epoch [7/40] Training loss: 2.3103103638
--------------------------------------------------
Epoch [8/40] Training loss: 1.9406066140
--------------------------------------------------
Epoch [9/40] Training loss: 1.7693803509
--------------------------------------------------
Epoch [10/40] Training loss: 1.5985624592
--------------------------------------------------
Epoch [11/40] Training loss: 1.5673280756
--------------------------------------------------
Epoch [12/40] Training loss: 1.4535348117
--------------------------------------------------
Epoch [13/40] Training loss: 1.5290637612
--------------------------------------------------
Epoch [14/40] Training loss: 1.2792195082
--------------------------------------------------
Epoch [15/40] Training loss: 1.4253122608
--------------------------------------------------
Epoch [16/40] Training loss: 1.2096834282
--------------------------------------------------
Epoch [17/40] Training loss: 1.4484458168
--------------------------------------------------
Epoch [18/40] Training loss: 1.3098777632
--------------------------------------------------
Epoch [19/40] Training loss: 1.1164896290
--------------------------------------------------
Epoch [20/40] Training loss: 1.1491068800
--------------------------------------------------
Epoch [21/40] Training loss: 1.0977206131
--------------------------------------------------
Epoch [22/40] Training loss: 1.1600993077
--------------------------------------------------
Epoch [23/40] Training loss: 1.2480542759
--------------------------------------------------
Epoch [24/40] Training loss: 1.2118400435
--------------------------------------------------
Epoch [25/40] Training loss: 1.1199067930
--------------------------------------------------
Epoch [26/40] Training loss: 1.0696820120
--------------------------------------------------
Epoch [27/40] Training loss: 1.2704423666
--------------------------------------------------
Epoch [28/40] Training loss: 1.2000988026
--------------------------------------------------
Epoch [29/40] Training loss: 1.0688728690
--------------------------------------------------
Epoch [30/40] Training loss: 1.1796491543
--------------------------------------------------
Epoch [31/40] Training loss: 0.9660651684
--------------------------------------------------
Epoch [32/40] Training loss: 1.0152646502
--------------------------------------------------
Epoch [33/40] Training loss: 1.1201607982
--------------------------------------------------
Epoch [34/40] Training loss: 1.0161406100
--------------------------------------------------
Epoch [35/40] Training loss: 1.0293878913
--------------------------------------------------
Epoch [36/40] Training loss: 1.0357857645
--------------------------------------------------
Epoch [37/40] Training loss: 1.0802427232
--------------------------------------------------
Epoch [38/40] Training loss: 0.9741238058
--------------------------------------------------
Epoch [39/40] Training loss: 1.0493878722
--------------------------------------------------
Epoch [40/40] Training loss: 0.8740071257
--------------------------------------------------
TRAINING COMPLETE
Model is saved at: /Users/AFischer/Documents/PhD_onderzoek/term_preterm_database/output/model/2022-03-24_10-23_tcn_sample_entropy_final_train.pth
Model was saved at 40 epochs
Loading at epoch 40 saved model weights...
The number of correct predicted samples: 29/40
The number of correct predicted samples: 14/20
Total test pred: [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]
Total test labels: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
Total test prob: [0.65028405, 0.053920362, 0.10055549, 0.1030159, 0.034513354, 0.21210358, 0.23432454, 0.2593648, 0.63236874, 0.40615273, 0.14400473, 0.39919233, 0.6709341, 0.50792253, 0.6057502, 0.09391535, 0.0012055081, 0.35183206, 0.01848836, 0.60366374, 0.4827728, 0.11384315, 0.2714363, 0.37368688, 0.32083222, 0.8134991, 0.2266136, 0.18377237, 0.34769636, 0.09534126, 0.02878776, 0.024812879, 0.21863183, 0.1840551, 0.40858114, 0.20815343, 0.102141805, 0.0029150834, 0.93113434, 0.46796617, 0.22768067, 0.23875877, 0.20877579, 0.012726823, 0.5459977, 0.04056677, 0.23157567, 0.136683, 0.13535374, 0.48262092, 0.46303955, 0.009191101, 0.6338476, 0.52835286, 0.003569337, 0.078464635, 0.0035579738, 0.4100554, 0.07611039, 0.31088936]
Precision score: 0.09090909090909091
Recall score: 0.125
F1 score: 0.10526315789473685
Average precision score: 0.2748557307786959
AUC score: 0.5817307692307692
The number of rows with infinite numbers that will be replaced with zero is: 0
The number of rows with NA numbers that will be replaced with zero is: 0
/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/plotnine/geoms/geom_path.py:75: PlotnineWarning: geom_path: Removed 2 rows containing missing values.
/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/plotnine/geoms/geom_path.py:75: PlotnineWarning: geom_path: Removed 2 rows containing missing values.
wandb: Network error (ConnectionError), entering retry loop.
The number of data points before removing the first 3600 data points (per rec_id) is: 10655901
Process wandb_internal:
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 162, in wandb_internal
    thread.join()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/process.py", line 333, in _bootstrap
    threading._shutdown()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 149, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 397, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 167, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 387, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
The number of data points before removing the first 3600 data points (per rec_id) is: 10655901
The number of data points after removing the first 3600 data points (per rec_id) is: 9575901
The number of data points before removing the last 3600 data points (per rec_id) is: 9575901
The number of data points after removing the last 3600 data points (per rec_id) is: 8495901
The number of data points before removing the first 3600 data points (per rec_id) is: 10655901
The number of data points after removing the first 3600 data points (per rec_id) is: 9575901
The number of data points before removing the last 3600 data points (per rec_id) is: 9575901
The number of data points after removing the last 3600 data points (per rec_id) is: 8495901
/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/pyentrp/entropy.py:161: RuntimeWarning: invalid value encountered in true_divide
